### ISSUE TITLE
Queues

### ISSUE THREAD

**Issue by tehnewb** [RuneDocs/Documentation#14]
There is a statement under Strong queues that says a Strong queue will cancel a Weak queue, but Suspends a Normal queue? What exactly is suspending a queue? Also, what are AI queues?

**Comment by Tyluur** [comment]
@GregHib would be best able to answer.

**Comment by GregHib** [comment]
> There is a statement under Strong queues that says a Strong queue will cancel a Weak queue, but Suspends a Normal queue? What exactly is suspending a queue? 

To pause; suspending in the kotlin coroutine sense.
It was based on some tests where opening a bank delays poison hits indefinitely until the interface is closed.

> Also, what are AI queues?

🤷 it's mentioned in some runescript images released, the list provided is all I could find about them.

Note: The queue's page is just notes I made while researching the topic, it's not a source or truth and was never intended to be public in it's current state
